export const GET_ITEMS_REQUEST = 'GET_ITEMS_REQUEST'
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS'
export const GET_ITEMS_FAILURE = 'GET_ITEMS_FAILURE'

export const SEARCH_ITEMS_REQUEST = 'SEARCH_ITEMS_REQUEST'
export const SEARCH_ITEMS_SUCCESS = 'SEARCH_ITEMS_SUCCESS'
export const SEARCH_ITEMS_FAILURE = 'SEARCH_ITEMS_FAILURE'

export const ADD_ITEMS_REQUEST = 'ADD_ITEMS_REQUEST'
export const ADD_ITEMS_SUCCESS = 'ADD_ITEMS_SUCCESS'
export const ADD_ITEMS_FAILURE = 'ADD_ITEMS_FAILURE'

export const UPDATE_ITEMS_REQUEST = 'UPDATE_ITEMS_REQUEST'
export const UPDATE_ITEMS_SUCCESS = 'UPDATE_ITEMS_SUCCESS'
export const UPDATE_ITEMS_FAILURE = 'UPDATE_ITEMS_FAILURE'

export const DELETE_ITEMS_REQUEST = 'DELETE_ITEMS_REQUEST'
export const DELETE_ITEMS_SUCCESS = 'DELETE_ITEMS_SUCCESS'
export const DELETE_ITEMS_FAILURE = 'DELETE_ITEMS_FAILURE'



export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAILURE = 'GET_STUDENT_FAILURE'

export const SEARCH_STUDENT_REQUEST = 'SEARCH_STUDENT_REQUEST'
export const SEARCH_STUDENT_SUCCESS = 'SEARCH_STUDENT_SUCCESS'
export const SEARCH_STUDENT_FAILURE = 'SEARCH_STUDENT_FAILURE'

export const ADD_STUDENT_REQUEST = 'ADD_STUDENT_REQUEST'
export const ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS'
export const ADD_STUDENT_FAILURE = 'ADD_STUDENT_FAILURE'

export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE'

export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST'
export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE'